version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: badgehunters
      POSTGRES_PASSWORD: badgehunters
      POSTGRES_DB: badgehunters
    ports:
      - "5432:5432"
    volumes:
      - badgehunters_pg:/var/lib/postgresql/data

volumes:
  badgehunters_pg:
